# Generated by Django 5.0.7 on 2024-07-24 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_forum_title_rename_text_post_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content'], name='main_post_content_c7669a_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['title'], name='main_thread_title_c78f79_idx'),
        ),
    ]
